ame: Vprofile actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: action/checkout@v4

      - name: Maven test 
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Set Java 11
        uses: action/setup-java@v3
        with 
          distribution: 'temurin'
          java-version: 11

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: sonar-scanner
          -Dsonar.host.url=${{secret.SONAR.URL}}
          -Dsonar.login=${{secret.SONAR.TOKEN}}
          -Dsonar.organization=${{secret.SONAR.ORGANIZATION}}
          -Dsonar.projectKey=${{secret.SONAR.PROJECT_KEY}}
          -Dsonar.sources=src/
          -Dsonar.junit.reportsPath=target/surefire-reports/
          -Dsonar.jacoco.reportsPath=target/jacoco.exe
          -Dsonar.java.checkstyle.reportsPath=target/checkstyle-result.xml
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:  
          SONAR_TOKEN: ${{secret.SONAR.TOKEN}}
          SONAR_HOST_URL: ${{secret.SONAR.URL}}


      